### PR TITLE
[GitHub-Actions] Add Nvidia (PGI) HPC Compiler.

### PR DESCRIPTION
**Pull request by ChinouneMehdi**

### CODE REVIEW

**Comment by tclune** [comment]
nvfortran is able to build and run pfunit now?    That's a pleasant surprise.

Isn't a block of code needed in `./cmake/nvfortran.cmake`  (or whatever name cmake reports as the vendor)?

**Comment by ChinouneMehdi** [comment]
> nvfortran is able to build and run pfunit now? That's a pleasant surprise.
> 
> Isn't a block of code needed in `./cmake/nvfortran.cmake` (or whatever name cmake reports as the vendor)?

CMake still identify Nvfortran Vendor as PGI.

**Comment by ChinouneMehdi** [comment]
The failure is due gFTL-shared submodule not updated.

**Comment by tclune** [comment]
OK - last time I looked there were far more fundamental issues with the OO aspects of pFunit.   But those were long ago masked by the gFTL-shared.

Thanks again.

**Review by tclune — APPROVED** [review]

**Comment by ChinouneMehdi** [comment]
The failure was due a removed compilation option, but even after I have pushed a fix, the compiler couldn't complete successfully.
It was working last time I tried (a week ago).

**Comment by mathomp4** [comment]
@ChinouneMehdi If you want to "fix" the Intel test, I think you might want to do:
```
          ctest -j1 -E fhamcrest --output-on-failure --repeat until-pass:4
```
I believe @tclune says there is a known bug he's filed with Intel.

**Comment by tclune** [comment]
OK - that's fine.     We may be able investigate further on our end if we can get the computing center to install the latest compiler.      I'll leave this open for now.

**Comment by ChinouneMehdi** [comment]
> @ChinouneMehdi If you want to "fix" the Intel test, I think you might want to do:
> 
> ```
>           ctest -j1 -E fhamcrest --output-on-failure --repeat until-pass:4
> ```
> 
> I believe @tclune says there is a known bug he's filed with Intel.

I was talking about the failure with Nvidia Compiler.

**Comment by ChinouneMehdi** [comment]
> The failure was due a removed compilation option, but even after I have pushed a fix, the compiler couldn't complete successfully.
> It was working last time I tried (a week ago).

I was mistaken, The only thing that was working is cmake configuration.

**Comment by ChinouneMehdi** [comment]
After some investigations, It looks like Nvidia Fortran has many bugs related to Oriented-Objects, and I don't think they will fix them in the near future.

**Pull request closed without merging**
