### PR TITLE
Prepend namespace to PFUNIT_LIBRARIES

### PR DESCRIPTION
**Pull request by kvrigor**
I get the following error when running `./build_with_cmake_and_run.x` on any of the examples at [pFUnit_demos](https://github.com/Goddard-Fortran-Ecosystem/pFUnit_demos):

`Fatal Error: Cannot open module file ‘funit.mod’ for reading at (1): No such file or directory`

The top-level [CMakeLists.txt](https://github.com/Goddard-Fortran-Ecosystem/pFUnit/blob/main/CMakeLists.txt#L186) specifies the `PFUNIT::` namespace for exported targets. Hence, `pfunit` and `funit` should be referenced as `PFUNIT::pfunit` and `PFUNIT::funit` on CMake macros/scripts. An example correct usage can be found at [PFUNITConfig.cmake.in](https://github.com/Goddard-Fortran-Ecosystem/pFUnit/blob/main/cmake/PFUNITConfig.cmake.in#L40):

```cmake
if (PFUNIT_BUILD_SHARED AND BUILD_SHARED_LIBS)
  set (PFUNIT_LIBRARIES PFUNIT::funit_shared)
  if (NOT PFUNIT_SKIP_MPI)
    list(APPEND PFUNIT_LIBRARIES PFUNIT::pfunit_shared)
  endif()
else()
  set (PFUNIT_LIBRARIES PFUNIT::funit)
  if (NOT PFUNIT_SKIP_MPI)
    list(APPEND PFUNIT_LIBRARIES PFUNIT::pfunit)
  endif()
endif()
```

### CODE REVIEW

**Comment by tclune** [comment]
First, apologies for the delayed response.    I had some email difficulties due to being forced to change email clients and many emails from mailing lists got buried.   (Still have not gotten all of my filters working under the new client.)

I will try to reproduce the issue this weekend.     I suspect you are correct, and that recent contributed changes to pFUnit are breaking the demos.     This was not the intent.

**Comment by kurtsansom** [comment]
I am having this same issue.

**Comment by tclune** [comment]
Unfortunately the fix is a bit tricky.      I spent the day fixing some build issues in the submodules that conflict with building pFUnit as separate CMake projects,  but that breaks the build of pFUnit when built using nested git submodules.    I've contacted the contributor for these changes, and depending on his response,  I'll fix things one way or the other.   But will probably be 2-3 more days.

**Comment by ZedThree** [comment]
This is at least part of the fix necessary to support all the use cases (nested submodules, external installation, and `FetchContent`)

**Comment by kvrigor** [comment]
> Unfortunately the fix is a bit tricky. I spent the day fixing some build issues in the submodules that conflict with building pFUnit as separate CMake projects, but that breaks the build of pFUnit when built using nested git submodules. I've contacted the contributor for these changes, and depending on his response, I'll fix things one way or the other. But will probably be 2-3 more days.

No problem, thanks for looking into this!

**Comment by tclune** [comment]
There was one unrelated issue to the demos, and once that hotfix is merged, this should all work again.

Over the weekend I'll go through the stack and create official releases and carefully update the submodules and such.   So by Monday AM it should be seemless.   Many thanks to @ZedThree and @mathomp4 for helping to get this straightened out.

**Comment by tclune** [comment]
I think this PR is now redundant.   I'll close, but please reopen if you still find an issue.

**Pull request closed without merging**
