### PR TITLE
Fixes #28 - ESMF support.

### LINKED ISSUE #28: add support for testing ESMF components
Extensions exist in other projects.    Should bring those into framework as optional.

### PR DESCRIPTION
**Pull request by tclune**
Basic integration of test subclasses that enable running ESMF GridComp
methods within a unit test.

Path specification is currently a bit klunky, but should be functional.

### CODE REVIEW

**Comment by mathomp4** [comment]
Weird. Only one of the tests failed. I'm going to press the "restart job" button to see if it was just a glitch as the other macOS test ran fine.

**Comment by mathomp4** [comment]
Seemed to pass now. I wonder why the status hasn't reported back...?

**Comment by tclune** [comment]
A similar thing happened with a pull request over the weekend.    Not sure if the problem is with GitHub/Travis or something in our travis.yml has rotted with time.

**Comment by tclune** [comment]
Approving with  failing tests.   The issue is with travis, not the code.

**Pull request merged**
