### PR TITLE
Draft: Update pFUnit to use v2 template interfaces

### LINKED ISSUE #463: compiler error:  v1 and v2 getting mixed together?
I'm trying to get pFunit compiling using the Cray CCE compiler, and I'm getting an odd error in the compile of FUnit_Core.F90:
```
ftn-487 ftn: ERROR FUNIT_CORE, File = ../../../../usr/WS2/cferenba/pFUnit/pFUnit-4.8.0/src/funit/core/FUnit_Core.F90, Line = 29, Column = 8 
  The specific interfaces for "M_NEW_MAP_EMPTY" and "MAP_NEW_MAP_EMPTY" make the GENERIC interface "STRINGUNLIMITEDMAP" ambiguous.
```
The offending source line is:
```
   use gFTL_StringUnlimitedMap
```
and the compile line that gave the error is:
```
/opt/cray/pe/craype/2.7.31.11/bin/ftn \
  -I/usr/WS2/cferenba/pFUnit/pFUnit-4.8.0/src/funit/core \
  -I/usr/WS2/cferenba/pFUnit/pFUnit-4.8.0/build-cce-17.0.1-ninja/src/funit/mod \
  -I/usr/WS2/cferenba/pFUnit/pFUnit-4.8.0/include \
  -I/usr/WS2/cferenba/pFUnit/pFUnit-4.8.0/build-cce-17.0.1-ninja/src/funit/core \
  -I/usr/WS2/cferenba/pFUnit/pFUnit-4.8.0/build-cce-17.0.1-ninja/extern/fArgParse/extern/gFTL-shared/extern/gFTL/include/v1 \
  -I/usr/WS2/cferenba/pFUnit/pFUnit-4.8.0/build-cce-17.0.1-ninja/extern/fArgParse/extern/gFTL-shared/src/v1/mod \
  -I/usr/WS2/cferenba/pFUnit/pFUnit-4.8.0/build-cce-17.0.1-ninja/extern/fArgParse/mod \
  -I/usr/WS2/cferenba/pFUnit/pFUnit-4.8.0/build-cce-17.0.1-ninja/extern/fArgParse/extern/gFTL-shared/extern/gFTL/include/v2 \
  -I/usr/WS2/cferenba/pFUnit/pFUnit-4.8.0/extern/fArgParse/extern/gFTL-shared/extern/gFTL/include/v2 \
  -I/usr/WS2/cferenba/pFUnit/pFUnit-4.8.0/build-cce-17.0.1-ninja/extern/fArgParse/extern/gFTL-shared/src/v2/mod \
  -g \
  -eZ \
  -O0 \
  -em \
  -em \
  -Jsrc/funit/mod \
  -h PIC \
  -c src/funit/core/CMakeFiles/funit-core.dir/FUnit_Core.F90-pp.f90 \
  -o src/funit/core/CMakeFiles/funit-core.dir/FUnit_Core.F90.o
```
As best I can tell, the issue is that there are two different (and incompatible) versions of the StringUnlimitedMap module being generated:
```
./extern/fArgParse/extern/gFTL-shared/src/v1/mod/GFTL_STRINGUNLIMITEDMAP.mod
./extern/fArgParse/extern/gFTL-shared/src/v2/mod/GFTL_STRINGUNLIMITEDMAP.mod
```
and somehow both of these are getting pulled into the build (note that the v1/mod and v2/mod paths are both showing up as include directories in the compile line above).

I'm not sure what to do about this.  Is the build really supposed to include both v1 and v2 directories?  And if so, how is the compiler supposed to disambiguate between them?

### PR DESCRIPTION
**Pull request by cferenba**
This adds the changes needed for pFUnit to build using the v2 versions of the template interfaces.

Note that this PR depends on Goddard-Fortran-Ecosystem/fArgParse#142 and will not build without it.

Resolves #463.

### CODE REVIEW

**Comment by cferenba** [comment]
Sorry, I got pulled aside to other things and haven't gotten back to this.  @tclune please review...

**Comment by tclune** [comment]
Same here. Vacation combined with official travel.   I have the ticket pegged in my inbox.  Hopefully can review sometime this week.  Quite jet-lagged at the moment though.

**Comment by cferenba** [comment]
> Quite jet-lagged at the moment though.

Understood.  Whenever you are able to get to it is fine.

**Review by tclune — APPROVED** [review]

**Comment by tclune** [comment]
@cferenba Sorry for the delay.  Finally got around to reviewing.  Looks fine but CI looks to have had a weird issue.  I'll discuss with my software stack person (@mathomp4) tomorrow.

**Comment by cferenba** [comment]
Looks like the CI is looking for an fArgParse hash that is in Goddard-Fortran-Ecosystem/fArgParse#142 but isn't in develop yet.

**Comment by tclune** [comment]
> Looks like the CI is looking for an fArgParse hash that is in [Goddard-Fortran-Ecosystem/fArgParse#142](https://github.com/Goddard-Fortran-Ecosystem/fArgParse/pull/142) but isn't in develop yet.

Yeah - should have read the "conversation" rather than just staring at the changes.     I've approved the fArgParse PR, but you'll need to at least touch the ChangeLog for CI to be happy there.   If the branch were local I would have done that for you.

**Review by tclune — APPROVED** [review]

**Comment by tclune** [comment]
I've created a new PR that brings in your changes to fArgParse.  Closing this one.

**Pull request closed without merging**
