### PR TITLE
fix: allow for long subroutine names in allocate

### LINKED ISSUE #294: long test function names
I am refactoring some code from fruit to pfunit and I have a test function name `populate_mappings_with_multiple_key_value_lines` which generates a line that is longer than 132 characters

```fortran
   if(allocated(t)) deallocate(t)
   allocate(t, source=TestMethod('populate_mappings_with_multiple_key_value_lines', populate_mappings_with_multiple_key_value_lines))
   call suite%addTest(t)
```

The solution is to shorten the name of the function, but is there an easier way to deal with this error or maybe change the code generation to use line continuation? I will create a merge request if you can point me where to put it.

also, Identifying the location of the error message is super vague.

```
Error: Line truncated at (1) [-Werror=line-truncation]
/tests/unit_tests/inputs/fortran_yaml_reader_tests/yaml_file_reader_tests.f90:465:132:

Error: Syntax error in ALLOCATE statement at (1)
f951: some warnings being treated as errors
tests/unit_tests/inputs/fortran_yaml_reader_tests/CMakeFiles/fortran_yaml_test.dir/build.make:78: recipe for target 'tests/unit_tests/inputs/fortran_yaml_reader_tests/CMakeFiles/fortran_yaml_test.dir/yaml_file_reader_tests.F90.o' failed
make[2]: *** [tests/unit_tests/inputs/fortran_yaml_reader_tests/CMakeFiles/fortran_yaml_test.dir/yaml_file_reader_tests.F90.o] Error 1
CMakeFiles/Makefile2:3247: recipe for target 'tests/unit_tests/inputs/fortran_yaml_reader_tests/CMakeFiles/fortran_yaml_test.dir/all' failed
make[1]: *** [tests/unit_tests/inputs/fortran_yaml_reader_tests/CMakeFiles/fortran_yaml_test.dir/all] Error 2
Makefile:165: recipe for target 'all' failed
make: *** [all] Error 2
```

Thank you for your time.

### PR DESCRIPTION
**Pull request by kurtsansom**
Create a subroutine test with the maximum fortran 2003 length (63 characters) and compile without errors.

Resolves #294

### CODE REVIEW

**Comment by tclune** [comment]
I must wait for the lawyer to confirm a signed CLA from external contributors.     For now, I've not looked at your solution, so I may be able to accidentally provide similar functionality in a separate PR.   Sigh.

**Comment by kurtsansom** [comment]
I sent the CLA this morning via docusign.

**Comment by tclune** [comment]
OK - thanks for the heads up.  The lawyer indicated that she usually turns these around in 2-3 days.   So far I've not seen any, but the only other confirmed submission is just from Friday.

**Comment by tclune** [comment]
Sorry I had not realized this PR never got merged.

**Comment by tclune** [comment]
Oh - right.  The CLA ...

**Pull request merged**
